In [2]:
import os
import sys

module_path = os.path.abspath(os.path.join('..'))
print(module_path)
if module_path not in sys.path:
    sys.path.append(module_path)
    
from src.data.collect_all import get_schedule_and_weekly_data

C:\Users\joshu\nfl-predictions

In [9]:
# get every number from 1999 to 2021
years = range(1999, 2022)

[1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021]

In [11]:
df = get_schedule_and_weekly_data(list(range(1999, 2022)))

Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.
Downcasting floats.

In [12]:
df

,game_id,season,game_type,week,opp_team,opp_score,target_team,target_score,div_game,target_days_since_previous_game,...,def_target_racr,def_target_racr_cumulative_average,def_target_racr_cumulative_average_change,def_target_wopr,def_target_wopr_cumulative_average,def_target_wopr_cumulative_average_change,def_target_special_teams_tds,def_target_special_teams_tds_cumulative_average,def_target_special_teams_tds_cumulative_average_change,is_home_target
0,1999_01_MIN_ATL,1999,REG,1,MIN,17.0,ATL,14.0,0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,1999_01_KC_CHI,1999,REG,1,KC,17.0,CHI,20.0,0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,1999_01_PIT_CLE,1999,REG,1,PIT,43.0,CLE,0.0,1,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,1999_01_BUF_IND,1999,REG,1,BUF,14.0,IND,31.0,1,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,1999_01_SF_JAX,1999,REG,1,SF,3.0,JAX,41.0,0,240.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10509,2021_20_LA_TB,2021,DIV,20,TB,27.0,LA,30.0,0,6.0,...,2.457977,7.459597,-0.294213,2.2,2.2,3.739899e-08,0.0,0.000000,0.000000,0
10510,2021_20_BUF_KC,2021,DIV,20,KC,42.0,BUF,36.0,0,8.0,...,-27.866425,4.572684,-1.908183,2.2,2.2,-1.745286e-07,0.0,0.000000,0.000000,0
10511,2021_21_CIN_KC,2021,CON,21,KC,24.0,CIN,27.0,0,8.0,...,3.311301,11.858133,-0.474824,2.2,2.2,4.461634e-08,0.0,0.000000,0.000000,0
10512,2021_21_SF_LA,2021,CON,21,LA,20.0,SF,17.0,1,8.0,...,7.835165,5.224143,0.145056,2.2,2.2,-1.673113e-07,0.0,0.052632,-0.002924,0
10513,2021_22_LA_CIN,2021,SB,22,CIN,20.0,LA,23.0,0,14.0,...,15.890073,7.407248,0.446465,2.2,2.2,4.015471e-08,0.0,0.000000,0.000000,0

In [14]:
df[df['game_id'] == '2000_01_SF_ATL']

,game_id,season,game_type,week,opp_team,opp_score,target_team,target_score,div_game,target_days_since_previous_game,...,def_target_racr,def_target_racr_cumulative_average,def_target_racr_cumulative_average_change,def_target_wopr,def_target_wopr_cumulative_average,def_target_wopr_cumulative_average_change,def_target_special_teams_tds,def_target_special_teams_tds_cumulative_average,def_target_special_teams_tds_cumulative_average_change,is_home_target
210,2000_01_SF_ATL,2000,REG,1,SF,28.0,ATL,36.0,1,240.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1250,-0.008333,1
5467,2000_01_SF_ATL,2000,REG,1,ATL,36.0,SF,28.0,1,240.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.1875,0.054167,0

In [24]:
df[(df['target_team'] == 'ARI') & (df['week'].isin([17, 1, 2])) & df['season'].isin([2000, 2001])]

,game_id,season,game_type,week,opp_team,opp_score,target_team,target_score,div_game,target_days_since_previous_game,...,def_target_racr,def_target_racr_cumulative_average,def_target_racr_cumulative_average_change,def_target_wopr,def_target_wopr_cumulative_average,def_target_wopr_cumulative_average_change,def_target_special_teams_tds,def_target_special_teams_tds_cumulative_average,def_target_special_teams_tds_cumulative_average_change,is_home_target
233,2000_02_DAL_ARI,2000,REG,2,DAL,31.0,ARI,32.0,1,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1
441,2001_02_DEN_ARI,2001,REG,2,DEN,38.0,ARI,17.0,0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.062500,-0.004167,1
5473,2000_01_ARI_NYG,2000,REG,1,NYG,21.0,ARI,16.0,1,240.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.125000,0.058333,0
5666,2000_17_ARI_WAS,2000,REG,17,WAS,20.0,ARI,3.0,1,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.066667,-0.004762,0
5874,2001_17_ARI_WAS,2001,REG,17,WAS,20.0,ARI,17.0,1,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.066667,-0.004762,0