In [1]:
import pandas as pd

In [ ]:
TARGET = 'target_win'

In [2]:
MODEL_FEATURES_BEFORE_RFE = pd.read_csv('../../../data/predict_games/model_features_in/xgb_features_list.csv')
INPUT_DATA = pd.read_parquet('../../../data/predict_games/input_data/schedule_and_weekly.parquet')

In [3]:
MODEL_FEATURES_BEFORE_RFE

                                               feature
0                                               season
1                                                 week
2                                             div_game
3                      target_days_since_previous_game
4                          target_off_cumulative_score
..                                                 ...
341                       def_target_special_teams_tds
342    def_target_special_teams_tds_cumulative_average
343  def_target_special_teams_tds_cumulative_averag...
344                                     is_home_target
345                                         target_win

[346 rows x 1 columns]

In [4]:
INPUT_DATA

,game_id,season,week,opp_team,opp_score,target_team,target_score,div_game,target_days_since_previous_game,target_off_cumulative_score,...,def_target_racr_cumulative_average,def_target_racr_cumulative_average_change,def_target_wopr,def_target_wopr_cumulative_average,def_target_wopr_cumulative_average_change,def_target_special_teams_tds,def_target_special_teams_tds_cumulative_average,def_target_special_teams_tds_cumulative_average_change,is_home_target,target_win
0,2003_02_WAS_ATL,2003,2,WAS,33.0,ATL,31.0,0,7.0,27.0,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,-0.062500,1,0
1,2003_02_CLE_BAL,2003,2,CLE,13.0,BAL,33.0,1,7.0,15.0,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,-0.062500,1,1
2,2003_02_DET_GB,2003,2,DET,6.0,GB,31.0,1,7.0,25.0,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,-0.125000,1,1
3,2003_02_TEN_IND,2003,2,TEN,7.0,IND,33.0,1,7.0,9.0,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,-0.066667,1,1
4,2003_02_PIT_KC,2003,2,PIT,20.0,KC,41.0,0,7.0,27.0,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,0.000000,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10773,2023_18_DEN_LV,2023,18,LV,27.0,DEN,14.0,1,7.0,343.0,...,7.170630,-0.305807,2.2,2.2,4.768372e-08,0.0,0.0000,0.000000,0,0
10774,2023_18_PHI_NYG,2023,18,NYG,27.0,PHI,10.0,1,7.0,423.0,...,15.925632,-0.091976,2.2,2.2,4.768372e-08,0.0,0.0000,0.000000,0,0
10775,2023_18_LA_SF,2023,18,SF,20.0,LA,21.0,1,7.0,383.0,...,10.673484,-0.055119,2.2,2.2,4.768372e-08,0.0,0.0000,0.000000,0,1
10776,2023_18_DAL_WAS,2023,18,WAS,10.0,DAL,38.0,1,8.0,471.0,...,5.111406,0.396310,2.2,2.2,4.768372e-08,0.0,0.0000,0.000000,0,1
10777,2023_18_BUF_MIA,2023,18,MIA,14.0,BUF,21.0,1,7.0,430.0,...,1.329556,-3.295651,2.2,2.2,4.768372e-08,1.0,0.0625,0.062500,0,1

In [6]:
model_inputs_df = INPUT_DATA[MODEL_FEATURES_BEFORE_RFE['feature']]
model_inputs_df

,season,week,div_game,target_days_since_previous_game,target_off_cumulative_score,target_off_cumulative_avg_score,target_off_cumulative_avg_score_change,opp_days_since_previous_game,opp_off_cumulative_score,opp_off_cumulative_avg_score,...,def_target_racr_cumulative_average,def_target_racr_cumulative_average_change,def_target_wopr,def_target_wopr_cumulative_average,def_target_wopr_cumulative_average_change,def_target_special_teams_tds,def_target_special_teams_tds_cumulative_average,def_target_special_teams_tds_cumulative_average_change,is_home_target,target_win
0,2003,2,0,7.0,27.0,27.0000,0.000000,10.0,16.0,16.0000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,-0.062500,1,0
1,2003,2,1,7.0,15.0,15.0000,0.000000,7.0,6.0,6.0000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,-0.062500,1,1
2,2003,2,1,7.0,25.0,25.0000,0.000000,7.0,42.0,42.0000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,-0.125000,1,1
3,2003,2,1,7.0,9.0,9.0000,0.000000,7.0,25.0,25.0000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,-0.066667,1,1
4,2003,2,0,7.0,27.0,27.0000,0.000000,7.0,34.0,34.0000,...,0.000000,0.000000,0.0,0.0,0.000000e+00,0.0,0.0000,0.000000,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10773,2023,18,1,7.0,343.0,21.4375,-0.362500,7.0,305.0,19.0625,...,7.170630,-0.305807,2.2,2.2,4.768372e-08,0.0,0.0000,0.000000,0,0
10774,2023,18,1,7.0,423.0,26.4375,0.304167,7.0,239.0,14.9375,...,15.925632,-0.091976,2.2,2.2,4.768372e-08,0.0,0.0000,0.000000,0,0
10775,2023,18,1,7.0,383.0,23.9375,0.137500,7.0,471.0,29.4375,...,10.673484,-0.055119,2.2,2.2,4.768372e-08,0.0,0.0000,0.000000,0,1
10776,2023,18,1,8.0,471.0,29.4375,-0.629167,7.0,319.0,19.9375,...,5.111406,0.396310,2.2,2.2,4.768372e-08,0.0,0.0000,0.000000,0,1
10777,2023,18,1,7.0,430.0,26.8750,0.008333,7.0,482.0,30.1250,...,1.329556,-3.295651,2.2,2.2,4.768372e-08,1.0,0.0625,0.062500,0,1

# Create train, holdout

In [7]:
# Train is all games before the 2023 season, holdout is 2023
train_df = model_inputs_df[model_inputs_df['season'] < 2023]
test_df = model_inputs_df[model_inputs_df['season'] == 2023]
X_train

# Begin Recursive Feature Elimination